const io = require('./Utils/io');
const vm = require('./Utils/vm');
const out = require('./Utils/out');

const ANSI = {
  reset: '\x1b[0m',
  green: '\x1b[32m',
  red: '\x1b[31m',
  yellow: '\x1b[33m',
  cyan: '\x1b[36m',
};

const OUT_HDR = '--[ this file was generated by oxygen Deobf | https://discord.gg/UyqEkAWng ]\n\n';

function withHdr(code) {
  return OUT_HDR + String(code || '').replace(/^\uFEFF/, '');
}

function mkLog(enabled) {
  return (step, status, extra = '') => {
    if (!enabled) return;
    let col = ANSI.red;
    let tag = 'fail';
    if (status === true || status === 'ok') {
      col = ANSI.green;
      tag = 'ok';
    } else if (status === 'partial' || status === 'warn') {
      col = ANSI.yellow;
      tag = 'warn';
    }
    const tail = extra ? ` ${extra}` : '';
    process.stderr.write(`${col}[${step}] ${tag}${tail}${ANSI.reset}\n`);
  };
}

function walkp(root, fn) {
  const stop = fn(root);
  if (stop) return true;
  for (const child of root.prototypes) {
    if (child && walkp(child, fn)) return true;
  }
  return false;
}

function collectOpcodes(root) {
  const used = new Set();
  walkp(root, (p) => {
    for (const ins of p.instructions) {
      if (ins && !ins.skipped) used.add(ins.opcode);
    }
  });
  return used;
}

function guessFromIns(root, op) {
  let guess = 'UNKNOWN';
  walkp(root, (p) => {
    for (const ins of p.instructions) {
      if (ins && !ins.skipped && ins.opcode === op) {
        guess = vm.guessOp(ins);
        return true;
      }
    }
  });
  return guess;
}

function deobf(source, options = {}) {
  const log = mkLog(!!options.log);
  const src = String(source);
  const detection = io.det(src);
  if (!detection.matched && !options.force) {
    log('det', false, detection.reason || 'reject');
    const err = new Error(`det:${detection.reason || 'reject'}`);
    err.detection = detection;
    throw err;
  }
  const fam =
    detection.family === 'luaobfuscator-chaotic-good'
    ? 'good'
    : detection.family === 'luaobfuscator-chaotic-evil'
    ? 'evil'
    : detection.family === 'luaobfuscator-v1'
    ? 'v1'
    : detection.family || '?';
  log('det', true, fam);

  if (detection.family === 'luaobfuscator-chaotic-good') {
    let good;
    try {
      good = io.deobfGd(src);
      log('xor', true);
      log('cff', good.wrapperCff && good.wrapperCff.remaining <= 1 ? true : 'partial');
    } catch (e) {
      log('xor', false);
      throw e;
    }
    if (good.lua.includes('math.ldexp')) {
      log('recon', false, 'ldexp');
      const err = new Error('good:ldexp');
      err.detection = detection;
      throw err;
    }
    log('recon', true);
    const outStr = withHdr(good.lua);
    return {
      detection,
      protections: [],
      wrapperCff: good.wrapperCff,
      bytecode: null,
      vm: null,
      strings: good.strings,
      cfg: null,
      lifted: outStr,
      reconstructed: outStr,
      lua: outStr,
      disasm: '',
      rewrittenSource: good.lua,
    };
  }

  const isV1 = detection.family === 'luaobfuscator-v1';

  const wrapperCff = io.unflatCff(src);
  const flatSrc = wrapperCff.source;
  log(
    'cff',
    wrapperCff.replaced > 0 ? (wrapperCff.remaining <= 1 ? true : 'partial') : 'warn',
    `rep=${wrapperCff.replaced} rem=${wrapperCff.remaining}`
  );

  let bytecode;
  try {
    bytecode = io.xtrBc(src);
    log('bc', true, `${bytecode.bytesRead}/${bytecode.bytesTotal}`);
  } catch (e) {
    log('bc', false);
    throw e;
  }

  let strings;
  if (isV1) {
    strings = { outer: [], vm: [], rewrittenSource: flatSrc, outerReplaced: 0, summary: { outerCount: 0, vmCount: 0, outerReplaced: 0 } };
    if (bytecode.root) {
      strings.vm = io.decAllStr(flatSrc, bytecode.root).vm;
      strings.summary.vmCount = strings.vm.length;
    }
  } else {
    strings = io.decAllStr(flatSrc, bytecode.root);
  }
  const s = strings.summary || {};
  log('str', true, `outer=${s.outerCount || 0} vm=${s.vmCount || 0}`);

  let rewrittenSource = flatSrc;
  let wrapperAfter = { replaced: 0, statesTotal: 0, remaining: wrapperCff.remaining };
  if (strings.rewrittenSource && strings.rewrittenSource !== flatSrc) {
    rewrittenSource = strings.rewrittenSource;
    wrapperAfter = io.unflatCff(rewrittenSource);
    rewrittenSource = wrapperAfter.source;
  }

  const protections = io.invProt(src, {
    wrapperCff: {
      replaced: wrapperCff.replaced + (wrapperAfter.replaced || 0),
      remaining: wrapperAfter.remaining != null ? wrapperAfter.remaining : wrapperCff.remaining,
    },
  });

  let vmResult;
  try {
    vmResult = vm.anVm(rewrittenSource);
    const used = collectOpcodes(bytecode.root);
    let mapped = 0;
    for (const op of used) if (vmResult.opcodeMap[op]) mapped++;
    if (mapped < Math.max(3, Math.ceil(used.size * 0.35))) {
      const vmFlat = vm.anVm(flatSrc);
      let mappedFlat = 0;
      for (const op of used) if (vmFlat.opcodeMap[op]) mappedFlat++;
      if (mappedFlat > mapped) vmResult = vmFlat;
    }

    vm.refOpMap(bytecode.root, vmResult.opcodeMap);

    for (const op of used) {
      if (!vmResult.opcodeMap[op] || vmResult.opcodeMap[op].name === 'UNKNOWN') {
        const g = guessFromIns(bytecode.root, op);
        if (!vmResult.opcodeMap[op]) vmResult.opcodeMap[op] = { name: g, body: '' };
        else vmResult.opcodeMap[op].name = g;
      }
    }
    log('vm', true, `ops=${vmResult.opcodeCount} used=${used.size}`);
  } catch (e) {
    log('vm', false);
    throw e;
  }

  const used = collectOpcodes(bytecode.root);
  let reconstructed;
  let lifted;
  let disasm;
  let cfg;
  try {
    reconstructed = out.reconProg(bytecode.root, vmResult.opcodeMap, vmResult.closureLocalOp);
    lifted = out.liftProg(bytecode.root, vmResult.opcodeMap, vmResult.closureLocalOp);
    disasm = out.disasmPr(bytecode.root, vmResult.opcodeMap, vmResult.closureLocalOp);
    cfg = out.sumCfg(bytecode.root, vmResult.opcodeMap, vmResult.closureLocalOp);
    log('recon', true);
  } catch (e) {
    log('recon', false);
    throw e;
  }

  const outStr = withHdr(reconstructed);
  return {
    detection,
    protections,
    wrapperCff: {
      replaced: wrapperCff.replaced + (wrapperAfter.replaced || 0),
      statesTotal: (wrapperCff.statesTotal || 0) + (wrapperAfter.statesTotal || 0),
      remaining: wrapperAfter.remaining != null ? wrapperAfter.remaining : wrapperCff.remaining,
    },
    bytecode: {
      bytesRead: bytecode.bytesRead,
      bytesTotal: bytecode.bytesTotal,
      sentinel: bytecode.sentinel,
      xorCalls: bytecode.xorCalls,
      root: bytecode.root,
    },
    vm: {
      opcodeCount: vmResult.opcodeCount,
      closureLocalOp: vmResult.closureLocalOp,
      usedOpcodes: [...used],
      usedMap: Object.fromEntries(
        [...used].map((op) => [op, (vmResult.opcodeMap[op] && vmResult.opcodeMap[op].name) || 'UNKNOWN'])
      ),
      nameToOpcodes: vmResult.nameToOpcodes,
      opcodeMap: vmResult.opcodeMap,
    },
    strings: {
      outer: strings.outer,
      vm: strings.vm,
      summary: strings.summary,
      maps: (strings.vm || []).map((m) => ({
        path: m.path,
        index: m.index,
        key: m.key,
        decrypted: m.decrypted,
        score: m.score,
        singleByte: !!m.singleByte,
      })),
      rewrittenSource: options.includeRewrittenSource ? rewrittenSource : undefined,
    },
    cfg,
    lifted,
    reconstructed: outStr,
    lua: outStr,
    disasm,
    rewrittenSource,
  };
}

module.exports = { deobf };
